apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
      - name: story
        image: 8cox/kube-data:2
        env:
          - name: STORY_FOLDER
            # value: 'story'
            valueFrom:
              configMapKeyRef:
                name: story-env
                key: folder
        volumeMounts:
          - mountPath: /app/story
            name: story-volume
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
        - name: story-volume
          persistentVolumeClaim:
            claimName: story-pvc
          # emptyDir: {} # only works fine for one replica and bound data inside pod
          # hostPath: # bound data inside the node, won't persist data for multple nodes
          #   path: /app
          #   type: DirectoryOrCreate
            
